// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnoaluffzcdffqwbbyvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ub2FsdWZmemNkZmZxd2JieXZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMDY1MjksImV4cCI6MjA2NTc4MjUyOX0.Sf8eulvg3a100kvEOF-jWrAdSTIHl9ak6Hf4VhmfMAk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});